apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shovel.fullname" . }}
  labels:
  {{- include "shovel.labels" . | nindent 4 }}

data:
  SERVER_PORT: "{{ .Values.env.app.port}}"
  APPLICATION_NAME: {{ .Values.env.app.name }}